### ISSUE TITLE
Just wondering, why deprecate fontmin?

### ISSUE THREAD

**Issue by siaikin** [Lete114/rollup-plugin-font-minify#3]

**Comment by lete114** [comment]
What?

**Comment by siaikin** [comment]
this #1 pr deprecate fontmin. I'm thinking about whether to use fontmin or fonteditor-core or font-minify, so I'm wondering why you're deprecating fontmin.

**Comment by lete114** [comment]
The `fontmin` API is ill-conceived and more complicated, but it is also more powerful

I've repackaged `fonteditor-core` to make it easier to use. 

https://github.com/Lete114/font-minify

**Comment by lete114** [comment]
And `fontmin` doesn't work in browsers, only in nodejs. And `font-minify` can be used in any environment.

**Comment by siaikin** [comment]
Thank you very much for your quick reply. I looked at the documentation for fontmin and fonteditor-core, and as you said, fonteditor-core has a much clearer API.
